# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e91d8c53d6ab132ab7754ddc165a4c879b86e9dd6b91f76be94e6ee93696c5c10c0365b35dd5ccd9537383e17a9e17e26d1ebe3f626fdf7203956c57aec2931

test:
  secret_key_base: 83a1882346ba17d14e53cc60012571706c28b893f5acfec6488c83a8f1da671a0f11066cfff6da76889f32e2d86dd5de313af43a82926ff6be64760b172644d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
